Develop
iAryslanov/WorkoutDiary pull request #1
Opened 2020-04-24 05:52 UTC by iAryslanov

Почему при назначении constraint height for Image View в ячейке ImageTableCell.xib в консоль выводится сообщение о том, что он (constraint) мне не нужен? А без constraint height содержимое ячейки не видно, потому что она сжимается.

Сообщение в консоли:

2020-04-24 08:44:22.330871+0300 WorkoutDiary[49795:3108384] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x28069e9e0 UIImageView:0x102c2e4c0.height == 85   (active)>",
    "<NSLayoutConstraint:0x28069f890 V:[UIImageView:0x102c2e4c0]-(4)-|   (active, names: '|':UITableViewCellContentView:0x102c2d520 )>",
    "<NSLayoutConstraint:0x28069f980 V:|-(0)-[UIImageView:0x102c2e4c0]   (active, names: '|':UITableViewCellContentView:0x102c2d520 )>",
    "<NSLayoutConstraint:0x28069fe80 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x102c2d520.height == 89.3333   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x28069e9e0 UIImageView:0x102c2e4c0.height == 85   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

2020-04-24 12:58 UTC, fixique commented
Как и обещал по ячейке предложения как уйти от варнига. 

1. Не прижимать констрейнт к низу и не делать ячейку автоматически вычисляемой по высоте. Т.е. нужно определить метод делегата таблицы `heightForRow`. И там задать твои 90 поинтов. 
2. Не завязываться на высоту картинки, а сделать автоматический расчет на контсрейнтах лейбла. 
3. У констрейнта, который снизу картинки. Нажать на него и выбрать другой relation `Greater Than or Equal` подойдет.

2020-04-24 13:01 UTC, fixique requested changes

2020-04-24 13:01 UTC, fixique commented on WorkoutDiary/AppDelegate.swift
> + func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
Не вызывается из-за SceneDelegate. Эти методы теперь там, если ты используешь SceneDelegate.

2020-04-24 13:01 UTC, fixique commented on WorkoutDiary/ImageTableCell.swift
> +    @IBOutlet weak var customImageView: UIImageView!
Аутлеты лучше делать приватными, чтобы не давать возможность их изменять из вне.

2020-04-24 13:01 UTC, fixique commented on WorkoutDiary/ViewController.swift
> +        cell.textLabel?.text = trains[indexPath.row]
Лучше сделать аутлет приватным, а настройку делать с помощью метода `configure(with: train)`

2020-04-30 09:11 UTC, iAryslanov commented on WorkoutDiary/ViewController.swift
> +        cell.textLabel?.text = trains[indexPath.row]
Создать метод configure(with: train) и делать настройку отображения текста в ячейках таблицы в нём?

2020-04-30 09:13 UTC, iAryslanov commented on WorkoutDiary/ViewController.swift
> +        cell.textLabel?.text = trains[indexPath.row]
> Лучше сделать аутлет приватным, а настройку делать с помощью метода `configure(with: train)`

Создать метод configure(with: train) и делать настройку отображения текста в ячейках таблицы в нём?

2020-04-30 15:49 UTC, fixique commented on WorkoutDiary/ViewController.swift
> +        cell.textLabel?.text = trains[indexPath.row]
Да, вообще у нас и вообще не принято открывать какие-то проперти у разных view, потому что это может привести к не ожидаемому поведению. Например, в случае контроллера, кто-то захочет менять текст на экране из вне, а это не круто.

2020-05-07 09:39 UTC, merged